# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'mkgen' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mkgen
  pod 'MarkupKit'
  pod 'MAObjCRuntime'
  pod 'GRMustache'

  target 'mkgenTests' do
    inherit! :search_paths
    
    # Pods for testing
    # None.
  end

end
